services:
  producer:
    build: .
    stdin_open: true 
    tty: true        
    container_name: producer_twitch
    ports:
      - '8000:8000'
    restart: "always"
    command: python producer.py
    networks:
      - network1
    volumes:
      - ./app:/producer/app

networks:
  network1:
    name: mynetwork
    external: true

